### ISSUE TITLE
WorldChange 

### ISSUE THREAD

**Issue by WindUnwaken** [MLG-Fortress/ExtraHardMode#103]
`[05:24:18] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to ExtraHardMode v3.12.1
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.jar:git-Paper-1169]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:747) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:636) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:303) ~[patched_1.12.jar:git-Paper-1169]
	at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1262) ~[?:?]
	at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1229) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1089) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1424) ~[patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1229) ~[patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1169]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1169]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.IllegalArgumentException: Max health must be greater than 0
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setMaxHealth(CraftLivingEntity.java:117) ~[patched_1.12.jar:git-Paper-1169]
	at com.extrahardmode.features.monsters.Glydia.onPlayerChangeWorld(Glydia.java:364) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.jar:git-Paper-1169]
	... 26 more`

**Comment by RoboMWM** [comment]
Pretty sure someone posted this in the spigot discussion thread as well. Anyways, @erik1998 you need to not modify the dragon's health if they have ExtraHardMode disabled for that world.

@WindUnwaken could you also pastebin your config.yml and a list of worlds the Ender Dragon was in, that'd be great.

**Comment by RoboMWM** [comment]
Pretty sure someone posted this in the spigot discussion thread as well. Anyways, @erik1988 you need to not modify the dragon's health if they have ExtraHardMode disabled for that world.

@WindUnwaken could you also pastebin your config.yml and a list of worlds the Ender Dragon was in, that'd be great.

**Comment by WindUnwaken** [comment]
https://pastebin.com/XEF2KQGN
