### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [MLG-Fortress/ExtraHardMode#107]
logs
```
[06:56:15] [Server thread/INFO]: [ExtraHardMode] Enabling ExtraHardMode v3.12.1
[06:56:15] [Server thread/ERROR]: Error occurred while enabling ExtraHardMode v3.12.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/coreprotect/CoreProtect
	at com.extrahardmode.compatibility.CompatCoreProtect.getCoreProtect(CompatCoreProtect.java:52) ~[?:?]
	at com.extrahardmode.compatibility.CompatCoreProtect.<init>(CompatCoreProtect.java:22) ~[?:?]
	at com.extrahardmode.compatibility.CompatHandler.starting(CompatHandler.java:94) ~[?:?]
	at com.extrahardmode.ExtraHardMode.registerModule(ExtraHardMode.java:241) ~[?:?]
	at com.extrahardmode.ExtraHardMode.onEnable(ExtraHardMode.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.coreprotect.CoreProtect
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[patched_1.12.2.jar:git-Paper-1222]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 16 more
[06:56:15] [Server thread/INFO]: [ExtraHardMode] Disabling ExtraHardMode v3.12.1
```

java 9
paperspigot 1.12.2

**Comment by RoboMWM** [comment]
Update or remove CoreProtect, since I'm pretty sure CoreProtect failed to enable properly earlier in this log(thus EHM isn't really at fault here).

**Comment by RoboMWM** [comment]
Assuming fixed...
