### ISSUE TITLE
Plugin gives exception on CreatureSpawnEvent on Spigot 1.13

### ISSUE THREAD

**Issue by mirolm** [MLG-Fortress/ExtraHardMode#124]
I tried the plugin on 1.13 and it seems some portions of it work. For example applying effects on player if something happens.

Aside of this server log gets spammed with the below error:

```[18:50:59] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to ExtraHardMode v3.12.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:287) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.World.addEntity(World.java:900) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.WorldServer.addEntity(WorldServer.java:942) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.addEntity(CraftWorld.java:1243) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.spawn(CraftWorld.java:1250) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.spawn(CraftWorld.java:858) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.spawnEntity(CraftWorld.java:362) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at com.extrahardmode.module.EntityHelper.spawn(EntityHelper.java:248) [ExtraHardMode.jar:?]
        at com.extrahardmode.module.EntityHelper.spawnRandomMob(EntityHelper.java:292) [ExtraHardMode.jar:?]
        at com.extrahardmode.features.monsters.MonsterRules.onEntitySpawn(MonsterRules.java:98) [ExtraHardMode.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:287) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.World.addEntity(World.java:900) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.WorldServer.addEntity(WorldServer.java:942) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.SpawnerCreature.a(SpawnerCreature.java:178) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.WorldServer.doTick(WorldServer.java:278) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:940) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchFieldError: MUTATED_ROOFED_FOREST
        at com.extrahardmode.features.monsters.Vindicator.onEntitySpawn(Vindicator.java:62) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        ... 31 more
```

**Comment by RoboMWM** [comment]
Use three backticks instead of one for blocks of code/text. 

    ```your text block here```

**Comment by RoboMWM** [comment]
Hmm, unsure if this is the result of @erik1988's PR for replacing mobs in certain biomes...?

**Comment by mirolm** [comment]
I think i found it...

```Caused by: java.lang.NoSuchFieldError: MUTATED_ROOFED_FOREST
        at com.extrahardmode.features.monsters.Vindicator.onEntitySpawn(Vindicator.java:62) ~[?:?]
```

In file Vindicator.java on line 62 we check for Biome.MUTATED_ROOFED_FOREST, but in 1.13 this is no longer valid. See in https://minecraft.gamepedia.com/1.13-pre5 

It seems that constants change and this causes the exception on 1.13.

**Comment by RoboMWM** [comment]
Should be fixed in https://github.com/MLG-Fortress/ExtraHardMode/commit/c368c2a3a231dd9c2172b9d8f862c49a44f4a8a6
