### ISSUE TITLE
Blocks do not fall in 1.13

### ISSUE THREAD

**Issue by THENATHE** [MLG-Fortress/ExtraHardMode#125]
Seems to occur whenever a block is placed that would have gravity. 

``` 
[02:27:44] [Server thread/WARN]: [ExtraHardMode] Task #16 for ExtraHardMode v3.12.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
	at com.extrahardmode.module.BlockModule.applyPhysics(BlockModule.java:115) ~[?:?]
	at com.extrahardmode.task.BlockPhysicsCheckTask.run(BlockPhysicsCheckTask.java:101) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-69774b3-272426a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by RoboMWM** [comment]
Should be fixed in https://github.com/MLG-Fortress/ExtraHardMode/commit/c368c2a3a231dd9c2172b9d8f862c49a44f4a8a6
