### ISSUE TITLE
Coreprotect2 incompatible

### ISSUE THREAD

**Issue by Mikimoka** [MLG-Fortress/ExtraHardMode#126]
Using latest coreprotect2 (must have) for minecraft 1.12 gives this error at start:
`Error occurred while enabling ExtraHardMode v3.12.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/coreprotect/CoreProtect
        at com.extrahardmode.compatibility.CompatCoreProtect.getCoreProtect(CompatCoreProtect.java:52) ~[?:?]
        at com.extrahardmode.compatibility.CompatCoreProtect.<init>(CompatCoreProtect.java:22) ~[?:?]
        at com.extrahardmode.compatibility.CompatHandler.starting(CompatHandler.java:94) ~[?:?]
        at com.extrahardmode.ExtraHardMode.registerModule(ExtraHardMode.java:241) ~[?:?]
        at com.extrahardmode.ExtraHardMode.onEnable(ExtraHardMode.java:142) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1568]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1568]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1568]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1568]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1568]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1568]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1568]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1568]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1568]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1568]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: net.coreprotect.CoreProtect
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1568]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1568]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        ... 16 more
Disabling ExtraHardMode v3.12.1

**Comment by Mikimoka** [comment]
was using wrong version on coreprotect did not see this on log until now. It's working fine. This issue can be deleted.
