### ISSUE TITLE
UnsupportedOperationException when placing zombie skull block

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#142]
Spigot 1.13.2 latest
EWH 3.13.alpha.2

No idea what caused this. No player was harmed in the event.
```
[15:07:48 ERROR]: Could not pass event EntityDeathEvent to ExtraHardMode v3.13.alpha.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:434) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityZombie.die(EntityZombie.java:532) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(SourceFile:61) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityZombie.damageEntity(EntityZombie.java:248) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:227) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at org.mcmonkey.sentinel.SentinelWeaponHelper.punch(SentinelWeaponHelper.java:170) [Sentinel-1.7.2-b198.jar:?]
        at org.mcmonkey.sentinel.SentinelAttackHelper.tryAttack(SentinelAttackHelper.java:311) [Sentinel-1.7.2-b198.jar:?]
        at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:994) [Sentinel-1.7.2-b198.jar:?]
        at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1172) [Sentinel-1.7.2-b198.jar:?]
        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:428) [Citizens-2.0.24-b1590.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:283) [Citizens-2.0.24-b1590.jar:?]
        at net.citizensnpcs.nms.v1_13_R2.entity.WolfController$EntityWolfNPC.mobTick(WolfController.java:187) [Citizens-2.0.24-b1590.jar:?]
        at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:665) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityLiving.k(EntityLiving.java:2256) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityInsentient.k(EntityInsentient.java:509) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityAgeable.k(EntityAgeable.java:145) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityAnimal.k(EntityAnimal.java:27) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityWolf.k(EntityWolf.java:143) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2100) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:247) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.EntityWolf.tick(EntityWolf.java:158) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1347) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1181) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.UnsupportedOperationException: Must change block type
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftSkull.setSkullType(CraftSkull.java:154) ~[spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        at com.extrahardmode.features.monsters.Zombies.onEntityDeath(Zombies.java:141) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor474.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar-2018-10-31-0637:git-Spigot-e4d0c66-aed3aec]
        ... 35 more
```

**Comment by SlimeDog** [comment]
On review, the death was probably caused by a Sentinel wolf. No indication which entity (type) died.

Sentinel 1.7.2-b198
Citizens 2.0.24-b1590

**Comment by RoboMWM** [comment]
more like a sentinel wolf died, but anyways I'll investigate when I can, thanks. Definitely related to citizens though since it's in the stacktrace.

**Comment by SlimeDog** [comment]
That's possible, but all my sentinels are invulnerable, and respawn, so I cannot say for sure.

**Comment by SlimeDog** [comment]
Happened again. It looks like one of my Wolf Sentinels killed a Zombie.

**Comment by SlimeDog** [comment]
Error still present in 3.13.beta

**Comment by RoboMWM** [comment]
Yea, I haven't looked at it yet. It's not in the 1.13 board since my guess is that it's not necessarily a 1.13 issue.

**Comment by RoboMWM** [comment]
Hmm, not sure if this was a 1.13 thing or something else. The method is deprecated, but if it doesn't work I'm not sure why/md_5 left it in...

**Comment by RoboMWM** [comment]
Also, this isn't an NPE (stands for NullPointerException).

**Comment by SlimeDog** [comment]
You're right. EventException caused by UnsupportedOperationException. Apologies for inaccuracy.
