### ISSUE TITLE
Snow causes error

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#149]
Spigot 1.13.2 latest
ExtraHardMode 3.13.1-59445b0
PyroWeather 2.1.3

In a snowy environment (SNOWY_TAIGA_MOUNTAINS):
```
[08:27:13 WARN]: [ExtraHardMode] Task #3038 for ExtraHardMode v3.13.1-59445b0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData cannot be cast to org.bukkit.block.data.type.Snow
        at com.extrahardmode.task.RemoveExposedTorchesTask.run(RemoveExposedTorchesTask.java:151) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[08:28:32 WARN]: [ExtraHardMode] Task #3143 for ExtraHardMode v3.13.1-59445b0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData cannot be cast to org.bukkit.block.data.type.Snow
        at com.extrahardmode.task.RemoveExposedTorchesTask.run(RemoveExposedTorchesTask.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[08:31:01 WARN]: [ExtraHardMode] Task #3341 for ExtraHardMode v3.13.1-59445b0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData cannot be cast to org.bukkit.block.data.type.Snow
        at com.extrahardmode.task.RemoveExposedTorchesTask.run(RemoveExposedTorchesTask.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-12-05-0713:git-Spigot-26a8d99-20fc5be]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[08:31:59 WARN]: [ExtraHardMode] Task #3419 for ExtraHardMode v3.13.1-59445b0 generated an exception
java.lang.ClassCastException: null
```
Snow may be manipulated by PyroWeather, but I thought to start here, since the error is cast in EHM code.

**Comment by RoboMWM** [comment]
Need the full stacktrace. Java/CB will cut off stacktraces that are repeatedly printed. Try to find the first time this exception occurred, that one will usually have the full stacktrace.

**Comment by SlimeDog** [comment]
That was the complete trace. Nothing additional about the ClassCastException with configuration _ExtraHardMode.Debug:true_. But these are logged occasionally:
```
[23:47:22 INFO]: [ExtraHardMode] SPIDER's drops at Location{world=CraftWorld{name=world_yellowdog},x=-1447.5,y=38.0,z=7333.5,pitch=0.0,yaw=10.197258} was cleared (was from a spawner or environmental damage was >50% )
[23:47:45 WARN]: [ExtraHardMode] Task #16801 for ExtraHardMode v3.13.1-59445b0 generated an exception
java.lang.ClassCastException: null
[23:47:53 WARN]: [ExtraHardMode] Task #16812 for ExtraHardMode v3.13.1-59445b0 generated an exception
java.lang.ClassCastException: null
[23:48:08 INFO]: [ExtraHardMode] SPIDER's drops at Location{world=CraftWorld{name=world_yellowdog},x=-1392.5,y=27.0,z=7232.5,pitch=0.0,yaw=256.68588} was cleared (was from a spawner or environmental damage was >50% )
[23:48:21 INFO]: [ExtraHardMode] SPIDER's drops at Location{world=CraftWorld{name=world_yellowdog},x=-1373.5,y=45.0,z=7384.5,pitch=0.0,yaw=127.30589} was cleared (was from a spawner or environmental damage was >50% )
```
The spider drop locations are near to my location, but 20-40 meters below me, underground.

**Comment by RoboMWM** [comment]
That's weird, idk what that other plugin does, maybe it hooks into the server and changes stuff, or... well I think what I had before then should've worked. (I think I'm supposed to be using snow layers, not blocks, and I was setting it as Material.SNOW before so...)

**Comment by RoboMWM** [comment]
Try https://github.com/MLG-Fortress/ExtraHardMode/commit/b55af08e5c9d58912fda9bc40fcedb7755b450f4, or if you want to help investigate further, see if it happens with https://github.com/MLG-Fortress/ExtraHardMode/commit/99dfec1ea110ba182a53f8ff1599bd35e41543ae

**Comment by SlimeDog** [comment]
It does not occur with 99dfec1.
