### ISSUE TITLE
IllegalArgumentException manipulating inventory

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#177]
Spigot 1.14.3
EHM 3.14.alpha-3fc941c

```
[09:35:51] [Server thread/WARN]: [ExtraHardMode] Task #122343 for ExtraHardMode v3.14.alpha-3fc941c generated an exception
java.lang.IllegalArgumentException: Attempted to get MORE_FALLING_BLOCKS of type LIST as a List<Material>.
        at com.extrahardmode.service.config.MultiWorldConfig.getMaterialList(MultiWorldConfig.java:468) ~[?:?]
        at com.extrahardmode.task.BlockPhysicsCheckTask.run(BlockPhysicsCheckTask.java:93) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.3.jar-2019-06-30-0607:git-Spigot-935adb3-a0e4747]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.3.jar-2019-06-30-0607:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1011) [spigot-1.14.3.jar-2019-06-30-0607:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar-2019-06-30-0607:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar-2019-06-30-0607:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar-2019-06-30-0607:git-Spigot-935adb3-a0e4747]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by RoboMWM** [comment]
While manipulating inventory? Seems more like while digging.

Not sure how I'm gonna reconcile things expecting a specific type of List, since I can't do instanceof with generics. Hmm.

**Comment by SlimeDog** [comment]
I don't recall digging at the time. I'll try again.

**Comment by RoboMWM** [comment]
No need to, the stacktrace should be sufficient here.

**Comment by SlimeDog** [comment]
OK. Thanks.

**Comment by SlimeDog** [comment]
With 009e5c7, I cannot get this to recur. Since I do not have a good reproduction case, it is difficult to confirm positively.
