### ISSUE TITLE
Console error index out of bounds

### ISSUE THREAD

**Issue by Pilvinen** [MLG-Fortress/ExtraHardMode#18]
I saw this EHM error in the logs:

```xml
[15:38:05] [Server thread/WARN]: [ExtraHardMode] Task #18 for ExtraHardMode v3.6.7 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 16
        at net.minecraft.server.v1_9_R1.Chunk.getBrightness(Chunk.java:532) ~[spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.getLightFromSky(CraftBlock.java:170) ~[spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at com.extrahardmode.task.MoreMonstersTask.verifyLocation(MoreMonstersTask.java:156) ~[?:?]
        at com.extrahardmode.task.MoreMonstersTask.run(MoreMonstersTask.java:127) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-b39373b-73eff0d]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by RoboMWM** [comment]
Next time add the markdown I just added to your report so the log is readable (use YML for YAML files, etc.)

**Comment by RoboMWM** [comment]
This appears to be a spigot bug. If it happens on the latest spigot version (since they've been rapidly updating every day), let me know and I'll file a report at their bug tracker

**Comment by RoboMWM** [comment]
This actually might be EHM trying to check a block above y=255, @kemmeo reported a similar issue.
