### ISSUE TITLE
Still using some old getonlineplayers methods

### ISSUE THREAD

**Issue by Pilvinen** [MLG-Fortress/ExtraHardMode#19]
Found this on console in the EHM v3.7:

```log
[15:50:47] [Craft Scheduler Thread - 15/WARN]: org.apache.commons.lang.UnhandledException: Plugin ExtraHardMode v3.7 generated an exception while executing task 55
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.extrahardmode.metrics.Metrics.postPlugin(Metrics.java:335)
        at com.extrahardmode.metrics.Metrics.access$400(Metrics.java:57)
        at com.extrahardmode.metrics.Metrics$1.run(Metrics.java:223)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by RoboMWM** [comment]
Seems that plugins that get around this package metrics themselves instead of making it a dependency. I'll see what I can do.

**Comment by RoboMWM** [comment]
Please try this version and let me know if it works or not: https://github.com/MLG-Fortress/ExtraHardMode/releases/tag/v3.7.1-beta

**Comment by RoboMWM** [comment]
Did this work?

**Comment by Pilvinen** [comment]
I am unable to test this. My logs are filled with error and other spam at the moment making them really hard to read and that error didn't seem very regular.

**Comment by RoboMWM** [comment]
I'll assume this is fixed - reply and re-open here if that isn't the case.

**Comment by RoboMWM** [comment]
Ah, this is why - was wondering why the code seemed correct on GitHub: https://www.spigotmc.org/threads/mcstats-doesnt-like-1-9.127507/#post-1354356
