### ISSUE TITLE
Unregistered scoreboard component

### ISSUE THREAD

**Issue by voigtman** [MLG-Fortress/ExtraHardMode#193]
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
System Info: Java 12 (Java HotSpot(TM) 64-Bit Server VM 12.0.2+10) Host:  Mac OS X 10.13.6 (x86_64)
...

...
[03:01:35 WARN]: [ExtraHardMode] Material null does not exist. Please remove this entry from Mining.Inhibit Tunneling.
[03:01:53 WARN]: [ExtraHardMode] Task #11 for ExtraHardMode v3.14.0-c4a5263 generated an exception
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:137) ~[patched_1.14.4.jar:git-Paper-192]
	at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:45) ~[patched_1.14.4.jar:git-Paper-192]
	at de.diemex.scoreboardnotifier.PlayerNotificationHandler.updateIndexes(PlayerNotificationHandler.java:207) ~[?:?]
	at de.diemex.scoreboardnotifier.PlayerNotificationHandler.displayMessage(PlayerNotificationHandler.java:141) ~[?:?]
	at de.diemex.scoreboardnotifier.NotificationManager.show_Popup(NotificationManager.java:51) ~[?:?]
	at de.diemex.scoreboardnotifier.NotificationManager.showTimedPopup(NotificationManager.java:72) ~[?:?]
	at de.diemex.scoreboardnotifier.NotificationManager.showPopup(NotificationManager.java:144) ~[?:?]
	at com.extrahardmode.module.MsgModule.sendPopup(MsgModule.java:327) ~[?:?]
	at com.extrahardmode.task.WeightCheckTask.run(WeightCheckTask.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-192]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-192]
	at java.lang.Thread.run(Thread.java:835) [?:?]
...
 
...
 ehm version
[03:02:37 INFO]: ========= ExtraHardMode =========
[03:02:37 INFO]: Version: 3.14.0-c4a5263
[03:02:37 INFO]: Author:
[03:02:37 INFO]:  - RoboMWM
[03:02:37 INFO]: Contributors:
[03:02:37 INFO]:  - Diemex
[03:02:37 INFO]:  - Big_Scary
[03:03:01 WARN]: Can't keep up! Is the server overloaded? Running 5007ms or 100 ticks behind
[03:03:46 WARN]: Can't keep up! Is the server overloaded? Running 14732ms or 294 ticks behind
[03:04:40 WARN]: Can't keep up! Is the server overloaded? Running 24063ms or 481 ticks behind
[03:05:43 WARN]: Can't keep up! Is the server overloaded? Running 33519ms or 670 ticks behind
...
 
...
[03:11:01 ERROR]: Could not pass event EntityTargetLivingEntityEvent to ExtraHardMode v3.14.0-c4a5263
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:137) ~[patched_1.14.4.jar:git-Paper-192]
	at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:45) ~[patched_1.14.4.jar:git-Paper-192]
	at de.diemex.scoreboardnotifier.PlayerNotificationHandler.updateIndexes(PlayerNotificationHandler.java:207) ~[?:?]
	at de.diemex.scoreboardnotifier.PlayerNotificationHandler.displayMessage(PlayerNotificationHandler.java:141) ~[?:?]
	at de.diemex.scoreboardnotifier.NotificationManager.show_Popup(NotificationManager.java:51) ~[?:?]
	at de.diemex.scoreboardnotifier.NotificationManager.showPopup(NotificationManager.java:124) ~[?:?]
	at com.extrahardmode.module.MsgModule.sendPopup(MsgModule.java:264) ~[?:?]
	at com.extrahardmode.module.MsgModule.send(MsgModule.java:123) ~[?:?]
	at com.extrahardmode.module.MsgModule.send(MsgModule.java:165) ~[?:?]
	at com.extrahardmode.features.Tutorial.onEntityTarget(Tutorial.java:153) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor270.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-192]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-192]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-192]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:168) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:55) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.c(SourceFile:41) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.a(SourceFile:75) ~[patched_1.14.4.jar:git-Paper-192]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:69) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:659) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2532) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityZombie.movementTick(EntityZombie.java:209) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2321) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityMonster.tick(EntityMonster.java:37) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:665) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:437) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-192]
	at java.lang.Thread.run(Thread.java:835) [?:?]

What happens is the scoreboard appears briefly then vanishes almost immediately. After some lag the error appears and the functionality of the plugin stops - at least for the hardened materials. I was trying the most current stable build from SpigotMC and then moved to this test build and the issue persists. 

What additional info do you need?

**Comment by RoboMWM** [comment]
> [03:01:35 WARN]: [ExtraHardMode] Material null does not exist. Please remove this entry from Mining.Inhibit Tunneling.

Try doing that first. Maybe regen your config or messages.yml. Idk if scoreboard stuff changed in 1.14, but I recall it working when I did test a fresh instance to fix some other bug (and iirc, yes it was the zombies message which is what it looks like is trying to be displayed here).

**Comment by voigtman** [comment]
Oh, sorry I missed that bit - there are no null entries in that section or any section.  I am getting this issue with the out-of-the-box installation.

**Comment by RoboMWM** [comment]
There's something wrong with your config. The `null` is incorrectly printed (as mentioned in the commit I just made), but it doesn't change the fact that there's still something wrong with your config in that section.

**Comment by voigtman** [comment]
Thank you for taking the time to help me - I'll admit I am trying to push the plugin to do something a bit different.
I am running some very basic tests at the moment - Is there a list of materials that cannot be hardened or used for a replacement block?

I'll tell you what my intention is - I would like to make the veins of granite, diorite, andesite and varieties of dirt to be hardened instead of normal stone. And instead of replacing them with cobble, I want them to remain the same material 
ie
`# Here you can specify custom stone blocks or change what stone softens into. (Stone@data-Cobble@data)
        Stone Blocks:
        - FARMLAND-DIRT
        - PODZOL-PODZOL
        - GRASS_BLOCK-GRASS_BLOCK`

**Comment by RoboMWM** [comment]
```yaml
    this is how you do a code block
    ```

Your material must exist in the materials enum. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by voigtman** [comment]
It appears one of the problems is an interaction with a plugin called Infernal Mobs. 
That solved the scoreboard issue - 
As for the blocks - I had gold_shovel not golden_shovel and that was causing the material error.

I do have one question now briefly while it was bugging out It would prevent me from punching the dirt - now that it's working I can still break the dirt with my fists but if I try any other tool it will not allow the dirt to break. is there currently a way to prevent the block from breaking with fists alone?

thank you for all of your help!

**Comment by RoboMWM** [comment]
Cool, thanks for updating on the scoreboard issue.

As for your other issues, perhaps you could try AIR? But you can't apply damage to the hand so idk. Either way, the whole point of that list is to contain what is _allowed_ to break the block so your idea isn't going to work.
