### ISSUE TITLE
3.6.7 placeblock error

### ISSUE THREAD

**Issue by LigerXT5** [MLG-Fortress/ExtraHardMode#20]
I know an update just came out for 3.7, however I haven't seen a notice of this being fixed. I figured I'd post it and see where it leads. If anything, it's an unneeded post.

```
[12:05:25] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to ExtraHardMode v3.6.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:142) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.ItemStack.placeItem(ItemStack.java:159) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:522) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:852) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoSuchFieldError: FIZZ
	at com.extrahardmode.features.Torches.onBlockPlace(Torches.java:105) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor505.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-87e2f47-ef13ca4]
	... 18 more
```

**Comment by RoboMWM** [comment]
Yup, fixed in 3.7. That's a 1.9 thing.
