### ISSUE TITLE
ExtraHardMode Console Error:

### ISSUE THREAD

**Issue by regix1** [MLG-Fortress/ExtraHardMode#275]
`[15:57:34 ERROR]: [ExtraHardMode] Task #376 for ExtraHardMode v3.14.2-3b567aa generated an exception
[15:57:34 ERROR]: [ExtraHardMode] Suspected Plugins: 
[15:57:34 ERROR]: [ExtraHardMode]       ExtraHardMode{enabled,ver=3.14.2-3b567aa,path=plugins/ExtraHardMode.jar}
[15:57:34 ERROR]: [ExtraHardMode] Exception details below: 
java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftObjective.checkState(CraftObjective.java:152) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:60) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at de.diemex.scoreboardnotifier.PlayerNotificationHandler.updateIndexes(PlayerNotificationHandler.java:207) ~[?:?]
        at de.diemex.scoreboardnotifier.PlayerNotificationHandler.displayMessage(PlayerNotificationHandler.java:141) ~[?:?]
        at de.diemex.scoreboardnotifier.NotificationManager.show_Popup(NotificationManager.java:51) ~[?:?]
        at de.diemex.scoreboardnotifier.NotificationManager.showTimedPopup(NotificationManager.java:72) ~[?:?]
        at de.diemex.scoreboardnotifier.NotificationManager.showPopup(NotificationManager.java:144) ~[?:?]
        at com.extrahardmode.module.MsgModule.sendPopup(MsgModule.java:327) ~[?:?]
        at com.extrahardmode.task.WeightCheckTask.run(WeightCheckTask.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1393) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:402) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1302) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1023) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-36]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by RoboMWM** [comment]
something unregistered the scoreboard?

**Comment by red0fireus** [comment]
I use featherboards as well, they seem to be fine together. Once the ExtraHardMode scoreboard disappears Fetherboards reappears. 

I'm looking at it now and the scoreboard is no longer appearing from ExtraHardMode. Unsure why it breaks now and not before. 
If this is going to be a problem, I could just disable the scoreboard for ExtraHardMode all together. 

Could I suggest that placeholders be added for ExtraHardMode so I can incorporate the messages in to featherboard? If not it's fine

**Comment by red0fireus** [comment]
Maybe something like %extrahardmode_messages% this would show all the messages from extrahardmode it would just be shown in a different scoreboard.

**Comment by RoboMWM** [comment]
I guess either another plugin or yatopia is messing with scoreboards then.
