### ISSUE TITLE
ExtraHardMode Console Error

### ISSUE THREAD

**Issue by VacAge** [MLG-Fortress/ExtraHardMode#291]
purpur-1.17.1-1428
ExtraHardMode-3.15.0
```
[16:55:18 ERROR]: Could not pass event BlockGrowEvent to ExtraHardMode v3.15.0-6ff295d
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
        at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:348) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getBiome(CraftRegionAccessor.java:202) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getBiome(CraftBlock.java:335) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.extrahardmode.module.BlockModule.plantDies(BlockModule.java:239) ~[ExtraHardMode-3.15.0.jar:?]
        at com.extrahardmode.features.AntiFarming.onBlockGrow(AntiFarming.java:184) ~[ExtraHardMode-3.15.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor508.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1229) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.level.block.CropBlock.randomTick(CropBlock.java:93) ~[app:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:923) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:999) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1050) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:935) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1652) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by alexchandel** [comment]
I get the same thing, issue is 1.18 support #290

**Comment by alexchandel** [comment]
@RoboMWM Do you still maintain this?
