### ISSUE TITLE
messages.yml - DISABLED not implemented

### ISSUE THREAD

**Issue by Aekalix** [MLG-Fortress/ExtraHardMode#50]
I get this error when a zombie attacks me:

```
[15:26:44] [Server thread/ERROR]: Could not pass event EntityTargetLivingEntityEvent to ExtraHardMode v3.8.5
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-a9631d2-2239ff0]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a9631d2-2239ff0]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:139) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.PathfinderGoalHurtByTarget.a(PathfinderGoalHurtByTarget.java:69) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.PathfinderGoalHurtByTarget.f(PathfinderGoalHurtByTarget.java:61) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.PathfinderGoalHurtByTarget.c(PathfinderGoalHurtByTarget.java:32) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.PathfinderGoalSelector.a(SourceFile:102) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityInsentient.doTick(EntityInsentient.java:664) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:1961) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityInsentient.n(EntityInsentient.java:512) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityMonster.n(EntityMonster.java:28) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityZombie.n(EntityZombie.java:176) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1817) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:240) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.EntityZombie.m(EntityZombie.java:233) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-a9631d2-2239ff0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.UnsupportedOperationException: DISABLED not implemented
at com.extrahardmode.module.MsgModule.send(MsgModule.java:135) ~[?:?]
at com.extrahardmode.module.MsgModule.send(MsgModule.java:163) ~[?:?]
at com.extrahardmode.features.Tutorial.onEntityTarget(Tutorial.java:154) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-a9631d2-2239ff0]
`
```

**Comment by RoboMWM** [comment]
Could you send me your messages.yml?

**Comment by RoboMWM** [comment]
@Aekalix it would be nice if you could paste your messages.yml so I can see where I need to fix this for future users.

**Comment by RoboMWM** [comment]
Confirmed an issue in duplicate issue #63
