### ISSUE TITLE
NPE on PlayerQuitEvent

### ISSUE THREAD

**Issue by mat41997** [MLG-Fortress/ExtraHardMode#54]
logs
http://pastebin.com/cXsAzSk7

**Comment by RoboMWM** [comment]
Pasting here to avoid pastebin.com's advertisements and other junk:

```
[15:06:39] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to ExtraHardMode v3.8.6
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-843]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-843]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-843]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-843]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.PlayerList.disconnect(PlayerList.java:408) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1069) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.NetworkManager.handleDisconnection(NetworkManager.java:318) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:186) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:886) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-843]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-843]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.extrahardmode.features.Players.onPlayerDisconnect(Players.java:382) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1482.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-843]
	... 13 more

**Comment by RoboMWM** [comment]
@mat41997, can you paste more of this log (when this player joined, or the entire log)? This error shouldn't happen unless either there was an error that occurred before this (or somehow the player quit so fast that playerjoinevent wasn't able to complete, but that doesn't sound possible).

**Comment by RoboMWM** [comment]
Without more logs, I can't determine what happened.

**Comment by RoboMWM** [comment]
Got this as well, I'm suspecting this is due to reloading the plugin. https://gist.github.com/RoboMWM/94dbf8bce4cf1fed5d2c6bb965a6c9da
