### ISSUE TITLE
witch potion error

### ISSUE THREAD

**Issue by random1167** [MLG-Fortress/ExtraHardMode#62]
```
[23:55:55 INFO]:  who's splashing postions
[23:56:01 ERROR]: Could not pass event PotionSplashEvent to ExtraHardMode v3.8.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:345) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.EntityPotion.a(EntityPotion.java:158) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.EntityPotion.a(EntityPotion.java:100) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.EntityProjectile.A_(EntityProjectile.java:167) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.UnsupportedOperationException: Not supported.
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftZombie.setVillager(CraftZombie.java:45) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        at com.extrahardmode.features.monsters.Witches.onPotionSplash(Witches.java:145) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
        ... 16 more
[23:56:03 INFO]: <player> witch
```

**Comment by RoboMWM** [comment]
Same as #70, closing this one as conversation is more active there
