### ISSUE TITLE
Disabling msg/tutorial does not work.

### ISSUE THREAD

**Issue by erik1988** [MLG-Fortress/ExtraHardMode#63]
I tried changing all msgs to "Mode: Disabled", but it gives me this error:

`[16:24:44] [Server thread/ERROR]: Could not pass event EntityTargetLivingEntityEvent to ExtraHardMode v3.8.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:143) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PathfinderGoalTarget.b(PathfinderGoalTarget.java:62) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:136) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:108) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:653) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2036) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityZombie.n(EntityZombie.java:155) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1892) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-e2a288c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.UnsupportedOperationException: DISABLED not implemented
	at com.extrahardmode.module.MsgModule.send(MsgModule.java:135) ~[?:?]
	at com.extrahardmode.module.MsgModule.send(MsgModule.java:163) ~[?:?]
	at com.extrahardmode.features.Tutorial.onEntityTarget(Tutorial.java:154) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7d78b81-e2a288c]
	... 24 more`

**Comment by erik1988** [comment]
I made a fork and fixed it.
https://github.com/MLG-Fortress/ExtraHardMode/pull/64

**Comment by RoboMWM** [comment]
Related to #50 ?

**Comment by erik1988** [comment]
Yeah they are the same. sorry i did not see that issue before making this.
